x-app: &default-app
  build:
    context: .
    target: "app"
    args:
      RAILS_ENV: ${RAILS_ENV:-production}
      POSTGRES_URL: ${POSTGRES_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      REDIS_URL: ${REDIS_URL}
  env_file:
    - .env
  stop_grace_period: 3s
  tty: true
  volumes:
    - ./public:/app/public
    - ./easy_ml:/app/easy_ml
  environment:
    RAILS_ENV: ${RAILS_ENV}
    SECRET_KEY_BASE: "${SECRET_KEY_BASE}" # Pass from host environment or .env file
    POSTGRES_URL: "${POSTGRES_URL}" # Pass from .env
    REDIS_URL: "${REDIS_URL}"

services:
  web:
    <<: *default-app
    healthcheck:
      test: "curl -f http://localhost:3000/easy_ml/healthcheck || exit 1"
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    ports:
      - "3000:3000" # Map container's port 3000 to host's port 3000
    profiles: ["web"]

  worker:
    <<: *default-app
    command: "bundle exec rake easy_ml:resque_pool"
    entrypoint: []
    profiles: ["worker"]

  resque-web:
    <<: *default-app
    command: "bundle exec resque-web -F"
    ports:
      - "5678:5678"
    profiles: ["resque-web"]
