test:
  adapter: postgresql
  database: easy_ml_test
  host: localhost
  port: 5432
  timeout: 5000

development:
  adapter: postgresql
  database: easy_ml_test
  host: localhost
  port: 5432
  timeout: 5000
